//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_AJAX的应用.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_orderdetails
    {
        public int id { get; set; }
        public int amount { get; set; }
        public int m_order_id { get; set; }
        public int m_product_id { get; set; }
    
        public virtual m_order m_order { get; set; }
        public virtual m_product m_product { get; set; }
    }
}
