//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_AJAX的应用.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class meixinEntities : DbContext
    {
        public meixinEntities()
            : base("name=meixinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_admin> m_admin { get; set; }
        public virtual DbSet<m_order> m_order { get; set; }
        public virtual DbSet<m_orderdetails> m_orderdetails { get; set; }
        public virtual DbSet<m_product> m_product { get; set; }
        public virtual DbSet<m_user> m_user { get; set; }
    }
}
